"""
Peer Review Auditor
===================
Implements the Generator-Critic cognitive architecture loop, providing multi-agent 
peer review auditing for high-impact outputs and plans before final execution.
"""

import logging
import json
from typing import Optional, Dict, Any
from dataclasses import dataclass

logger = logging.getLogger(__name__)

@dataclass
class AuditResult:
    """The outcome of a peer review audit."""
    accepted: bool
    confidence: float
    feedback: str


class PeerReviewAuditor:
    """
    Orchestrates the Generator-Critic review loop using static safety heuristics
    and semantic LLM peer-review validation.
    """

    def __init__(self, router: Optional[Any] = None, max_audit_iterations: int = 1):
        self._router = router
        self.max_audit_iterations = max_audit_iterations

    def audit(
        self, 
        proposed_artifact: str, 
        agent_name: str, 
        policy: Optional[str] = None
    ) -> AuditResult:
        """
        Audits a proposed artifact (plan, code, text response) from an agent.
        Returns an AuditResult indicating whether it is accepted and any feedback.
        """
        logger.info(f"[PeerReview] Auditing artifact from agent '{agent_name}'")

        # 1. Static Safety Audit (Heuristic Checks)
        artifact_lower = proposed_artifact.lower()
        if "rm -rf" in artifact_lower or "format c:" in artifact_lower or "drop table" in artifact_lower:
            logger.warning("[PeerReview] Static check FAILED: Destructive command detected.")
            return AuditResult(
                accepted=False,
                confidence=1.0,
                feedback="CRITICAL SAFETY VIOLATION: Destructive system command detected. Execution blocked."
            )

        # 2. Semantic LLM Audit
        if self._router:
            prompt = (
                f"You are the Peer Review Auditor (Critic) in a Generator-Critic loop.\n"
                f"Review the following proposed artifact generated by the agent '{agent_name}':\n\n"
                f"--- PROPOSED ARTIFACT ---\n"
                f"{proposed_artifact}\n"
                f"-------------------------\n\n"
            )
            if policy:
                prompt += f"Ensure compliance with this specific policy:\n{policy}\n\n"
            else:
                prompt += "Ensure the artifact is accurate, safe, high-quality, and directly addresses the goal.\n\n"

            prompt += (
                "Respond ONLY with a valid JSON block of this schema:\n"
                "{\n"
                '  "accepted": true/false,\n'
                '  "confidence": 0.0 to 1.0,\n'
                '  "feedback": "detailed review comments or correction guide"\n'
                "}\n"
                "Do not include any other text before or after the JSON."
            )

            try:
                decision = self._router.decide(
                    prompt=prompt,
                    context="You are the Critic validating proposed agent artifacts for safety and quality."
                )
                
                # Parse response JSON
                text = decision.message.strip() if hasattr(decision, "message") else str(decision)
                
                # Strip code blocks if LLM outputted markdown format
                if "```json" in text:
                    text = text.split("```json")[1].split("```")[0].strip()
                elif "```" in text:
                    text = text.split("```")[1].split("```")[0].strip()
                    
                data = json.loads(text)
                
                return AuditResult(
                    accepted=bool(data.get("accepted", True)),
                    confidence=float(data.get("confidence", 0.9)),
                    feedback=str(data.get("feedback", "No feedback provided."))
                )
            except Exception as e:
                logger.error(f"[PeerReview] LLM semantic audit failed: {e}")
                # Fallback to accepting if LLM fails, unless static checks failed
                return AuditResult(
                    accepted=True,
                    confidence=0.5,
                    feedback=f"LLM audit unavailable due to error: {e}. Static checks passed."
                )

        # No router: Default to pass if static checks pass
        return AuditResult(
            accepted=True,
            confidence=1.0,
            feedback="Static safety checks passed. Semantic review skipped (no router)."
        )
