"""
Ollama Live Debugger & Interactive Chat
=======================================
Launches an interactive chat session (>>>) that wraps the local Ollama LLM
and displays in real-time exactly:
  1. What system prompts, memory context, and user queries are sent to Ollama.
  2. How Ollama plans and makes decisions (raw JSON output & structured plans).
  3. What action/skills are executed.
  4. The final reply.

Run:
    python ollama_interactive_debugger.py
"""

import os
import sys
import logging
from pathlib import Path
from typing import Optional

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Silence standard system logging to make the debug panels readable
logging.basicConfig(level=logging.WARNING)
logging.getLogger("jarvis").setLevel(logging.WARNING)

from rich.console import Console
from rich.panel import Panel
from rich.text import Text
from rich.syntax import Syntax

from jarvis.main import build_orchestrator
from jarvis.llm.llm_interface import LLMInterface, Plan, LLMDecision
from jarvis.brain.message_formatter import MessageFormatter

console = Console()

class DebugLLMWrapper(LLMInterface):
    """
    Wraps the active LocalLLM instance to intercept and display
    exact prompt payloads and raw LLM outputs.
    """
    def __init__(self, real_llm: LLMInterface):
        self._real = real_llm

    @property
    def name(self) -> str:
        return f"debug_wrapper/{self._real.name}"

    def health_check(self) -> bool:
        return self._real.health_check()

    def plan(self, prompt: str, memory_context: str = "") -> Optional[Plan]:
        # Build the system instructions that will be sent
        system_instructions = self._real.build_system_prompt()
        
        # 1. Show exactly what goes to Ollama
        console.print(Panel(
            Text.assemble(
                ("🤖 SYSTEM INSTRUCTIONS INJECTED:\n", "bold cyan"),
                (system_instructions.strip(), "dim green"),
                ("\n\n🧠 RETRIEVED MEMORY CONTEXT:\n", "bold cyan"),
                (memory_context.strip() if memory_context.strip() else "[Empty]", "yellow"),
                ("\n\n👤 USER QUERY:\n", "bold cyan"),
                (prompt, "white bold")
            ),
            title="📥 PAYLOAD SENT TO OLLAMA (plan)",
            border_style="cyan"
        ))

        # 2. Get real response
        result = self._real.plan(prompt, memory_context)

        # 3. Show raw response
        plan_desc = ""
        if result:
            plan_desc = "\n".join(f"  • {item.skill} (params: {item.params})" for item in result)
        else:
            plan_desc = "  • None / Empty Plan"

        console.print(Panel(
            Text.assemble(
                ("📋 STRUCTURED PLAN GENERATED BY OLLAMA:\n", "bold green"),
                (plan_desc, "yellow")
            ),
            title="📤 RESPONSE FROM OLLAMA (plan)",
            border_style="green"
        ))
        
        return result

    def decide(self, prompt: str, context: str = "") -> Optional[LLMDecision]:
        # 1. Show exactly what goes to Ollama
        sys_prompt = (
            "You are JARVIS, an advanced AI desktop assistant.\n"
            "You must ALWAYS return a SINGLE valid JSON object and absolutely nothing else..."
        )
        console.print(Panel(
            Text.assemble(
                ("🤖 COGNITIVE DECISION SYSTEM PROMPT:\n", "bold cyan"),
                (sys_prompt, "dim green"),
                ("\n\n📡 LIVE METADATA / CONTEXT FUSION:\n", "bold cyan"),
                (context.strip() if context.strip() else "[None]", "yellow"),
                ("\n\n👤 USER QUERY:\n", "bold cyan"),
                (prompt, "white bold")
            ),
            title="📥 PAYLOAD SENT TO OLLAMA (decide)",
            border_style="magenta"
        ))

        # 2. Get real response
        result = self._real.decide(prompt, context)

        # 3. Show raw response
        if result:
            decision_json = {
                "type": result.type,
                "message": result.message,
                "question": result.question,
                "steps": [{"skill": s.skill, "params": s.params} for s in result.steps] if result.steps else None
            }
            import json
            pretty_json = json.dumps(decision_json, indent=2)
            raw_content = Syntax(pretty_json, "json", theme="monokai", line_numbers=False)
        else:
            raw_content = Text("Empty Decision Received", style="bold red")

        console.print(Panel(
            raw_content,
            title="📤 RAW JSON RESPONSE RECEIVED FROM OLLAMA (decide)",
            border_style="green"
        ))

        return result


def main():
    console.print(Panel(
        "[bold green]🛰 JARVIS OLLAMA INTERACTIVE DEBUGGER V1.0[/bold green]\n"
        "Connecting to local Ollama server... Please ensure ollama is running.",
        border_style="bold green"
    ))

    # 1. Build the orchestrator
    try:
        orch = build_orchestrator(use_ollama=True)
    except Exception as e:
        console.print(f"[bold red]❌ Failed to boot Jarvis Orchestrator:[/bold red] {e}")
        sys.exit(1)

    # 2. Inject our DebugLLMWrapper into the primary and active backends
    router = orch._router
    if router:
        router._primary = DebugLLMWrapper(router._primary)
        if router._fallback:
            router._fallback = DebugLLMWrapper(router._fallback)
        console.print("[bold green]✔ Debug wrapper injected into LLM Router successfully.[/bold green]\n")
    else:
        console.print("[bold red]❌ LLM Router not found in orchestrator. Cannot proceed.[/bold red]")
        sys.exit(1)

    # 3. Start Chat Loop
    console.print("[bold yellow]Type '/exit' or '/quit' to exit the debugger session.[/bold yellow]")
    console.print("[bold cyan]System is online. Ready for your command! [/bold cyan]\n")

    while True:
        try:
            # Styled prompt input
            text = console.input("[bold white]>>> [/bold white]").strip()
            if not text:
                continue

            if text.lower() in ("/exit", "/quit", "exit", "quit"):
                console.print("[bold red]Offline.[/bold red]")
                break

            console.print("\n[dim]🧠 Brain processing input...[/dim]")
            
            # Send message through the real Orchestrator's execution flow
            results = orch.process(text, source="cli")

            # Format and display the final reply
            reply_text = MessageFormatter.format(results, source="cli")
            console.print(Panel(
                Text(reply_text, style="bold green"),
                title="🤖 JARVIS FINAL REPLY",
                border_style="bold green"
            ))
            console.print()

        except KeyboardInterrupt:
            console.print("\n[bold red]Offline.[/bold red]")
            break
        except Exception as e:
            console.print(f"[bold red]Error encountered: {e}[/bold red]")


if __name__ == "__main__":
    main()
