"""
Chat Skill — Conversational AI Responses
=========================================
Pure pass-through skill for conversational replies generated by the LLM Unified Brain.
"""

import logging
from jarvis.skills.skill_decorator import skill
from jarvis.skills.skill_bus import SkillResult

logger = logging.getLogger(__name__)

@skill(
    triggers=["chat", "reply", "talk", "message"],
    name="chat_reply",
    category="session",
    is_cognitive=True,   # Never auto-learned as a macro
)
def chat_reply(params: dict) -> SkillResult:
    """
    Conversational response skill. Pure pass-through from the LLM.
    Requires 'message' parameter.
    """
    message = params.get("message", "I don't have a response for that right now.")
    logger.info(f"[chat_skill] Delivering reply: {message!r}")

    return SkillResult(
        success=True,
        message=message,
        action_taken="Delivered conversational reply",
    )
